FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the frontend code
COPY ./frontend ./frontend

# Streamlit's default port
EXPOSE 8080

# Run Streamlit and ensure it listens on all interfaces
CMD ["sh", "-c", "streamlit run frontend/app.py --server.port=${PORT:-8080} --server.address=0.0.0.0"]




